### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by lililuya** [River-Zhang/SIFU#46]
Impressive Work!!  I've encounter OOM in NVIDIA GeForce4090 24G GPU memory.
![image](https://github.com/user-attachments/assets/ecac534b-0e93-405c-ac44-3d5f4886af9c)
I checked the config, its content is as followed:
```yaml
name: sifu
ckpt_dir: "./data/ckpt/"
resume_path: "./data/ckpt/sifu.ckpt"
normal_path: "./data/ckpt/normal.ckpt"

test_mode: True
batch_size: 1

net:
  #mlp_dim: [512, 512, 256, 128, 1]
  mlp_dim: [512, 1024, 512, 256, 128, 1]
  mlp_dim_color: [512, 1024, 512, 256, 128, 3]
  res_layers: [2,3,4]
  num_stack: 2
  prior_type: "icon" # icon/pamir/icon
  use_filter: True
  in_geo: (('normal_F',3), ('normal_B',3))
  in_nml: (('image',3), ('T_normal_F',3), ('T_normal_B',3))
  smpl_feats: ['sdf', 'cmap', 'norm', 'vis','sample_id']
  gtype: 'HGPIFuNet'
  norm_mlp: 'batch'
  hourglass_dim: 6
  smpl_dim: 7

# user defined
mcube_res: 512    # occupancy field resolution, higher --> more details
clean_mesh: False # if True, will remove floating pieces
```
